on:
  workflow_call:
    inputs:
      pkg:
        required: true
        type: string
      is_build:
        required: false
        type: boolean
        default: true
      dir:
        required: false
        type: string
        default: out

jobs:
  deploy-to-pkg:
    name: ${{ inputs.pkg }}
    runs-on: ubuntu-latest
    steps:
      - uses: rwu823/actions@yarn-install-with-cache
      - run: yarn workspace @rwu823/${{ inputs.pkg }} build
        if: ${{ inputs.is_build }}
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          FOLDER: packages/${{ inputs.pkg }}/${{ inputs.dir }}
          BRANCH: pkg/${{ inputs.pkg }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
