name: Mono Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: rwu823/actions/eslint@latest
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: rwu823/actions/node-pnpm@latest
      - run: yarn vitest run packages/ts-base --coverage
      - uses: codecov/codecov-action@v3.1.6
        with:
          files: 'coverage/coverage-final.json'
      - uses: actions/upload-artifact@v3
        with:
          name: test coverage
          path: |
            coverage
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: rwu823/actions/node-pnpm@latest
      - run: npx playwright install-deps
      - run: yarn workspace @rwu823/dev-pptr e2e
  mono-deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rwu823/actions/node-pnpm@latest
      - run: npx ts-node scripts/monoDeploy
